pages: []
29Ge:
  - material: Onboarding-2025
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics-2025
    as: 03-BYOD-Basics
    ignore:
      - 99-Interviews-Repetition.mdx
  - material: Programmieren-2025
    as: 04-Programmieren
    ignore:
      - 04-Advent-of-Code
  - material: IN-Biber/2025
    as: 05-IN-Biber-2025
  - material: SOL-Text-Adventure-29Ge
    as: 06-SOL-Projekt-GYM1
  - material: Information-Daten-29Ge
    as: 07-Information-Daten
  - material: Textverarbeitung-Style-29Ge
    as: 08-Textverarbeitung-und-Style
  - material: Kryptologie-2026
    as: 09-Kryptologie
draft:
  - material: confidential/Probe-Data-Management-GYM28
    as: 99-Probe-Data-Management
  - material: confidential/Probe-Data-Management-GYM28-NP1
    as: 100-Probe-Data-Management-NP1
  - material: confidential/HackLab
    as: 101-HackLab
demo-probe:
  - material: confidential/ExamNet-Demo-Probe/index.mdx
    as: /index.mdx
29Fb:
  - material: Onboarding-2026
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics-2026
    as: 03-BYOD-Basics
    ignore: 
      - index-fms.mdx
  - material: BYOD-Basics-2026/index-fms.mdx
    as: 03-BYOD-Basics/index.mdx
29Fc:
  - material: Onboarding-2026
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics-2026
    as: 03-BYOD-Basics
    ignore: 
      - index-fms.mdx
  - material: BYOD-Basics-2026/index-fms.mdx
    as: 03-BYOD-Basics/index.mdx
30Gg:
  - material: Onboarding-2026
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: Programmieren-2026
    as: 03-Programmieren
  - material: BYOD-Basics-2026
    as: 03-BYOD-Basics
    ignore: 
      - index-fms.mdx
30Gh:
  - material: Onboarding-2026
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: Programmieren-2026
    as: 03-Programmieren
  - material: BYOD-Basics-2026
    as: 03-BYOD-Basics
    ignore: 
      - index-fms.mdx
30Gm:
  - material: Onboarding-2026
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: Programmieren-2026
    as: 03-Programmieren
  - material: BYOD-Basics-2026
    as: 03-BYOD-Basics
    ignore: 
      - index-fms.mdx
30Gw:
  - material: Onboarding-2026
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: Programmieren-2026
    as: 03-Programmieren
  - material: BYOD-Basics-2026
    as: 03-BYOD-Basics
    ignore: 
      - index-fms.mdx
30mT:
  - material: Onboarding-2026
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: Programmieren-2026
    as: 03-Programmieren
  - material: BYOD-Basics-2026
    as: 03-BYOD-Basics
    ignore: 
      - index-fms.mdx
