pages: []
28Ga:
  - material: Onboarding-2024
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics
    as: 03-BYOD-Basics
  - material: Programmieren-1
    as: 04-Programmieren-1
  - material: IN-Biber/2024
    as: 05-IN-Biber-2024
  - material: Information-Daten
    as: 06-Information-Daten
  - material: Textverarbeitung-Style
    as: 07-Textverarbeitung-und-Style
  - material: Repetition-2025/Repetition-GYM28-Lang.mdx
    as: 08-Repetition-IN-GYM1/index.mdx
  - material: Kryptologie
    as: 09-Kryptologie
  - material: Data-Management-2025
    as: 10-Data-Management
  - material: Netzwerke-2026
    as: 11-Netzwerke
    ignore:
      - 07-Routing
      - 51-Networking-the-Nerds.mdx
      - 60-Repetition.mdx
      - 70-Ausblicke
  - material: Abschlussprojekt-GYM28
    as: 12-Abschlussprojekt
  - material: Schnitzeljagd-GYM28
    as: 13-Schnitzeljagd
28Gd:
  - material: Onboarding-2024
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics
    as: 03-BYOD-Basics
  - material: Programmieren-1
    as: 04-Programmieren-1
  - material: IN-Biber/2024
    as: 05-IN-Biber-2024
  - material: Information-Daten
    as: 06-Information-Daten
  - material: Textverarbeitung-Style
    as: 07-Textverarbeitung-und-Style
  - material: Repetition-2025/Repetition-GYM28-Lang.mdx
    as: 08-Repetition-IN-GYM1/index.mdx
  - material: Kryptologie
    as: 09-Kryptologie
  - material: Data-Management-2025
    as: 10-Data-Management
  - material: Netzwerke-2026
    as: 11-Netzwerke
    ignore:
      - 07-Routing
      - 51-Networking-the-Nerds.mdx
      - 60-Repetition.mdx
      - 70-Ausblicke
  - material: Abschlussprojekt-GYM28
    as: 12-Abschlussprojekt
  - material: Schnitzeljagd-GYM28
    as: 13-Schnitzeljagd
28Gf:
  - material: Onboarding-2024
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics
    as: 03-BYOD-Basics
  - material: Programmieren-1
    as: 04-Programmieren-1
  - material: IN-Biber/2024
    as: 05-IN-Biber-2024
  - material: Information-Daten
    as: 06-Information-Daten
  - material: Textverarbeitung-Style
    as: 07-Textverarbeitung-und-Style
  - material: Repetition-2025/Repetition-GYM28-Kurz.mdx
    as: 08-Repetition-IN-GYM1/index.mdx
  - material: Kryptologie
    as: 09-Kryptologie
  - material: Data-Management-2025
    as: 10-Data-Management
  - material: Netzwerke-2026
    as: 11-Netzwerke
    ignore:
      - 07-Routing
      - 51-Networking-the-Nerds.mdx
      - 60-Repetition.mdx
      - 70-Ausblicke
  - material: Abschlussprojekt-GYM28
    as: Abschlussprojekt
  - material: Schnitzeljagd-GYM28
    as: 13-Schnitzeljagd
28Gh:
  - material: Onboarding-2024
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics
    as: 03-BYOD-Basics
  - material: Programmieren-1
    as: 04-Programmieren-1
  - material: IN-Biber/2024
    as: 05-IN-Biber-2024
  - material: Information-Daten
    as: 06-Information-Daten
  - material: Textverarbeitung-Style
    as: 07-Textverarbeitung-und-Style
  - material: Repetition-2025/Repetition-GYM28-Kurz.mdx
    as: 08-Repetition-IN-GYM1/index.mdx
  - material: Kryptologie
    as: 09-Kryptologie
  - material: Data-Management-2025
    as: 10-Data-Management
  - material: Netzwerke-2026
    as: 11-Netzwerke
    ignore:
      - 07-Routing
      - 60-Repetition.mdx
      - 70-Ausblicke
  - material: Abschlussprojekt-GYM28
    as: 12-Abschlussprojekt
  - material: Schnitzeljagd-GYM28
    as: 13-Schnitzeljagd
  - material: confidential/HackLab
    as: 14-HackLab
28mU:
  - material: Onboarding-2024
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics
    as: 03-BYOD-Basics
  - material: Programmieren-1
    as: 04-Programmieren-1
  - material: IN-Biber/2024
    as: 05-IN-Biber-2024
  - material: Information-Daten
    as: 06-Information-Daten
  - material: Textverarbeitung-Style
    as: 07-Textverarbeitung-und-Style
  - material: Repetition-2025/Repetition-GYM28-Kurz.mdx
    as: 08-Repetition-IN-GYM1/index.mdx
  - material: Kryptologie
    as: 09-Kryptologie
  - material: Data-Management-2025
    as: 10-Data-Management
  - material: Netzwerke-2026
    as: 11-Netzwerke
    ignore:
      - 07-Routing
      - 51-Networking-the-Nerds.mdx
      - 60-Repetition.mdx
      - 70-Ausblicke
  - material: Abschlussprojekt-GYM28
    as: 12-Abschlussprojekt
  - material: Schnitzeljagd-GYM28
    as: 13-Schnitzeljagd
29Ge:
  - material: MyGBSL
    as: 00-MyGBSL
  - material: Onboarding-2025
    as: 02-Onboarding
  - material: Erste-Hilfe
    as: 03-Erste-Hilfe
  - material: BYOD-Basics-2025
    as: 04-BYOD-Basics
    ignore:
      - 99-Interviews-Repetition.mdx
  - material: Programmieren-2025
    as: 05-Programmieren
    ignore:
      - 04-Advent-of-Code
  - material: IN-Biber/2025
    as: 06-IN-Biber-2025
  - material: SOL-Text-Adventure-29Ge
    as: 07-SOL-Projekt-GYM1
  - material: Information-Daten-29Ge
    as: 08-Information-Daten
  - material: Textverarbeitung-Style-29Ge
    as: 08-Textverarbeitung-und-Style
28Fa:
  - material: Onboarding-2025
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics-2025
    as: 03-BYOD-Basics
    ignore:
      - 01-Probe.mdx
      - 99-Interviews-Repetition.mdx
  - material: Programmieren-2025
    as: 04-Programmieren
    ignore:
      - 04-Advent-of-Code
  - material: IN-Biber/2025
    as: 05-IN-Biber-2025
  - material: Word-FMS28
    as: 06-Word
28Fb:
  - material: Onboarding-2025
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics-2025
    as: 03-BYOD-Basics
    ignore:
      - 01-Probe.mdx
      - 99-Interviews-Repetition.mdx
  - material: Programmieren-2025
    as: 04-Programmieren
    ignore:
      - 04-Advent-of-Code
  - material: IN-Biber/2025
    as: 05-IN-Biber-2025
  - material: Word-FMS28
    as: 06-Word
28Fc:
  - material: Onboarding-2025
    as: 01-Onboarding
  - material: Erste-Hilfe
    as: 02-Erste-Hilfe
  - material: BYOD-Basics-2025
    as: 03-BYOD-Basics
    ignore:
      - 01-Probe.mdx
  - material: Programmieren-2025
    as: 04-Programmieren
    ignore:
      - 04-Advent-of-Code
  - material: IN-Biber/2025
    as: 05-IN-Biber-2025
  - material: Word-FMS28
    as: 06-Word
draft:
  - material: confidential/Probe-Data-Management-GYM28
    as: 99-Probe-Data-Management
  - material: confidential/Probe-Data-Management-GYM28-NP1
    as: 100-Probe-Data-Management-NP1
  - material: confidential/HackLab
    as: 101-HackLab
demo-probe:
  - material: confidential/ExamNet-Demo-Probe/index.mdx
    as: /index.mdx
